
export const products = [
    {"id":1,"title":"Fifa23","price":19.99,"description":"The pinnacle of soccer gaming. Stunning graphics, authentic gameplay, and endless competition. Step onto the virtual pitch and become a legend!","category":"PS5","image":require('../assets/fifa23.jpg'),"rating":{"rate":3.9,"count":120}},
    {"id":2,"title":"Spiderman","price":22.3,"description":"Swing into action with Spider-Man! Unleash your web-slinging skills in a thrilling open-world adventure. Defend New York City, fight iconic villains, and become the hero the city needs","category":"PS4","image":require('../assets/spiderman.jpg'),"rating":{"rate":4.1,"count":259}},
    {"id":3,"title":"Call of Duty","price":55.99,"description":"Experience intense warfare in Call of Duty. Engage in heart-pounding battles across various eras and locations. Join the ranks and prove your skills in this iconic first-person shooter.","category":"PS4","image": require('../assets/callofduty.jpg'),"rating":{"rate":4.7,"count":500}},
    {"id":4,"title":"Diablo","price":15.99,"description":"Dive into darkness, battle demons, and become a legendary hero in Diablo's action-packed RPG world.","category":"PS5","image":require('../assets/diablo.jpg'),"rating":{"rate":2.1,"count":430}},
    {"id":5,"title":"Final Fantasy","price":695,"description":"Enter a fantastical world of magic and adventure in Final Fantasy. Join heroes on an epic quest, face mythical creatures, and unravel captivating stories in this iconic RPG series.","category":"PS5","image": require('../assets/finalfantasy.jpg'),"rating":{"rate":4.6,"count":400}},
    {"id":6,"title":"God of War ","price":168,"description":"Unleash Kratos, battle gods, and conquer epic mythology in God of War – the ultimate action adventure.","category":"PS4","image":require('../assets/godofwar.jpg'),"rating":{"rate":3.9,"count":70}},
    {"id":7,"title":"NBA 23","price":9.99,"description":"Dunk into the future with NBA 23! Experience next-gen basketball action, stunning graphics, and immersive gameplay. Take your team to the championship and redefine the game","category":"PS5","image":require('../assets/nba23.jpg'),"rating":{"rate":3,"count":400}},
    {"id":8,"title":"Wonderland","price":10.99,"description":"Enter Wonderland – a whimsical adventure awaits! Explore enchanting realms, solve puzzles, and meet quirky characters in this magical game.","category":"XBOX","image":require('../assets/wonderland.jpg'),"rating":{"rate":1.9,"count":100}},
    {"id":9,"title":"Spiderman 2","price":64,"description":"Swing back into action with Spider-Man 2! Dive into an open-world metropolis, fight iconic villains, and unleash incredible web-slinging skills in the ultimate superhero experience.","category":"PS5","image": require('../assets/spiderman.jpg'),"rating":{"rate":3.3,"count":203}},
    {"id":10,"title":"Fifa24","price":109,"description":"Dive into the world of soccer with FIFA 24! Experience lifelike graphics, thrilling gameplay, and endless competition. Build your dream team, score epic goals, and become a soccer legend.","category":"XBOX","image": require('../assets/fifa23.jpg'),"rating":{"rate":2.9,"count":470}}
    // Add more products as needed
  ];